language: ruby
bundler_args: --without development
rvm:
  - 2.0.0
  - 2.2.2
  - jruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby-head
sudo: false
addons:
  code_climate:
    repo_token: 185a714e42214b9369217d0ddfd5a02d528d9a616a34482119a16c63241d6afd
